#!/usr/bin/env sh

script_dir=$(realpath $(dirname "$0"))

#export CURSEFORGE_API_KEY='xxxx'

cd $script_dir/..

nix run "github:luochen1990/minecraft-mods/dev#update" -- --config-input ./config.json --config-output ./config.lock.json

